### ISSUE TITLE
Link to resume is broken, and link to report broken links is broken

### ISSUE THREAD

**Issue by trbrc** [rekkabell/kokorobot#15]
The resume link from the [about page](https://kokorobot.ca/site/about.html) is broken because of a missing slash:

https://github.com/rekkabell/kokorobot/blob/298aa1e2146e954ba64bf97bf785fa8f4d0f0dc4/site/about.html#L16

It should be `<a href="/media/content/resume.rekkabellum.pdf">`.

The 404 page that gets served instead asked me to report the broken link, but the link to report the broken link was also broken...!

https://github.com/rekkabell/kokorobot/blob/298aa1e2146e954ba64bf97bf785fa8f4d0f0dc4/404.html#L33

It should be `<a href='https://github.com/rekkabell/kokorobot/issues/new' …>`.

**Comment by rekkabell** [comment]
Fixed! Thx for reporting the broken links.
