### ISSUE TITLE
cerbellum missing

### ISSUE THREAD

**Issue by lcb931023** [rekkabell/kokorobot#18]
Is cerbellum still published on the site? I noticed that my old bookmark (https://kokorobot.ca/site/cerbellum.html) leads to 404 now.

**Comment by rekkabell** [comment]
Yep, it's still published under the project name Mindbird. Sorry about that, I changed the link: https://kokorobot.ca/site/mindbird.html

**Comment by lcb931023** [comment]
ooh glad to hear!
