### ISSUE TITLE
https://kokorobot.ca/site/rug.html doesn't exist

### ISSUE THREAD

**Issue by Munksgaard** [rekkabell/kokorobot#21]
[This page](https://kokorobot.ca/site/rug.html) seems to not exist, despite being linked to from the bottom of [this page](https://100r.co/site/liveaboard.html).

**Comment by rekkabell** [comment]
Oh yea, i changed a bunch of link names on my website and forgot I had a link to it on 100r.co. Link has been updated! Thx for reporting the broken link!
