### ISSUE TITLE
Missing link on sprite comissions page

### ISSUE THREAD

**Issue by Dakedres** [rekkabell/kokorobot#24]
On the [sprite comissions page](http://kokorobot.ca/site/sprite.html) there's a broken link at the very bottom, for Nekos. It's pointing to:

http://kokorobot.ca/media/content/project/sprite/gifs/sprite.31.jpg

Which is missing.

**Comment by Dakedres** [comment]
It also seems the link for Mary (http://kokorobot.ca/media/content/project/sprite/gifs/sprite.32.jpg ) is broken

**Comment by rekkabell** [comment]
Ah! Yes you're right :) there was some errors in the links. I've just corrected it. Thank you for reporting these~
